### ISSUE TITLE
Add static builds in the next release

### ISSUE THREAD

**Issue by jstoja** [EtixLabs/CES#7]
Right now the dynamic links make the usage a bit annoying just to fake a rtsp stream. If this can be statically compiled, it would help a lot imo.

**Comment by Ullaakut** [comment]
Did you look into it? Maybe @Gegonz can also do it since he was working on that recently. If none of you want to do it, I can do it but not now.

**Comment by jstoja** [comment]
I quickly did and @Gegonz told me that he knew what to do with cmake. So I let him handle that properly!

**Comment by Gegonz** [comment]
To do so we have to compile gst-rtsp-server + gst ugly plugin statically with is not recommanded (C functions not liking this + quite a nightmare to do).
We will make it available to run as a docker image to isolate the deps: https://github.com/EtixLabs/CES/issues/10
